---

- name: config
  vars:
    run_wsl: |
      ansible-playbook \
        --ask-become-pass \
        --inventory $PWD/ansible \
        $PWD/../../../linux/redhat-config/nfs-server/update-exports/ansible-playbook.config.yml
  hosts: nfs-server
  become: true
  tasks:

    - block:

      - name: mkdir for nfs exports
        loop: "{{ nfs_kernel.exports | map(attribute='dir') }}"
        ansible.builtin.file:
          state: directory
          path: "{{ item }}"
          mode: '0777'

      - name: ensure required entries are made to hosts file. # Notes 1232
        loop: "{{ nfs_kernel.exports }}"
        ansible.builtin.lineinfile:
          path: /etc/exports
          state: present
          create: yes
          line: "{{ item.dir }}  {{ item.conf }}"

      - name: start nfs service
        loop:
          - nfs-server
        ansible.builtin.service:
          name: "{{ item }}"
          enabled: true
          state: restarted
    
    - block:
    
      - name: mkdir mount dir
        ansible.builtin.file:
          path: "{{ nfs_kernel.test.mount_dir }}"
          state: directory
          mode: "{{ nfs_kernel.test.mount_permission }}"

      - name: mount point
        ansible.posix.mount:
          fstype: "{{ point_type }}"
          opts: "{{ nfs_kernel.test.point_opts }}"
          src: "{{ nfs_kernel.test.point_nfs }}"
          path: "{{ nfs_kernel.test.mount_dir }}"
          state: mounted

      - name: umount point
        ansible.posix.mount:
          path: "{{ nfs_kernel.test.mount_dir }}"
          state: unmounted

      - name: remove mount dir
        ansible.builtin.file:
          path: "{{ nfs_kernel.test.mount_dir }}"
          state: absent